#!/usr/bin/env node
/**
 * Generates src/model/game-db.ts from greeny/SatisfactoryTools' data.json
 * (already parsed, clean, 1.0+: correct names, fluid colors, endgame tier).
 *
 * Source: _data/greeny.json
 *   → https://raw.githubusercontent.com/greeny/SatisfactoryTools/dev/data/data.json
 *   (not versioned here: re-download it to regenerate.)
 *
 * Why not the raw Docs.json (dmryabov): its "alternative" format corrupts
 * ~35% of recipe mDisplayName values ("Fuel" on sulfuric acid…) and is still
 * stuck on Update 8. greeny is parsed from the official 1.0+ Docs.json.
 *
 *  - items   : id = kebab(name) [convention kept], name, state (liquid→fluide),
 *              color (fluidColor RGB for fluids, otherwise a hue derived from the slug)
 *  - recipes : recipes produced in a machine (inMachine && !forBuilding); rate /min
 *              = amount × 60 / time (greeny already normalizes units, fluids in m³)
 *  - BASE_ITEMS : raw resources (g.resources); INFINITE_ITEMS: water
 *
 * Slugs: item = kebab(display name); recipe = greeny.slug (= className in kebab-case,
 * identical to the old convention → keeps existing chains compatible).
 */
const fs = require("fs");
const path = require("path");

const g = JSON.parse(fs.readFileSync(path.join(__dirname, "greeny.json"), "utf8"));
const round = (n) => Math.round(n * 1000) / 1000;

const slugify = (s) =>
  String(s).toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function hslToHex(h, s, l) {
  s /= 100; l /= 100;
  const k = (n) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  const to = (x) => Math.round(255 * x).toString(16).padStart(2, "0");
  return `#${to(f(0))}${to(f(8))}${to(f(4))}`;
}
function solidColor(slug) {
  let h = 0;
  for (let i = 0; i < slug.length; i++) h = (h * 31 + slug.charCodeAt(i)) % 360;
  return hslToHex(h, 42, 62);
}
const hex2 = (x) => Math.max(0, Math.min(255, x | 0)).toString(16).padStart(2, "0");

// --- Items ---
const items = {};
const classToSlug = {}; // className (Desc_*) -> slug
for (const it of Object.values(g.items)) {
  const slug = slugify(it.name);
  if (!slug) continue;
  const fluid = !!it.liquid;
  const fc = it.fluidColor;
  const couleur =
    fluid && fc && (fc.r || fc.g || fc.b) ? `#${hex2(fc.r)}${hex2(fc.g)}${hex2(fc.b)}` : solidColor(slug);
  classToSlug[it.className] = slug;
  if (!items[slug]) items[slug] = { id: slug, nom: it.name, couleur, etat: fluid ? "fluide" : "solide" };
}

// --- Recipes produced in a machine ---
const buildings = g.buildings || {};
const recipes = {};
const missingItems = new Set();
const port = (p, time) => {
  const slug = classToSlug[p.item];
  if (!slug) missingItems.add(p.item);
  return { item: slug || slugify(p.item), debit: round((p.amount * 60) / time) };
};
for (const r of Object.values(g.recipes)) {
  if (!r.inMachine || r.forBuilding) continue;
  if (!r.time || r.time <= 0) continue;
  const machineClass = (r.producedIn || []).find((c) => buildings[c]);
  if (!machineClass) continue; // not an actual production machine
  recipes[r.slug] = {
    id: r.slug,
    nom: r.name,
    machine: buildings[machineClass].name,
    ...(r.alternate ? { alternative: true } : {}),
    intrants: (r.ingredients || []).map((p) => port(p, r.time)),
    extrants: (r.products || []).map((p) => port(p, r.time)),
  };
}

// --- Raw / unlimited resources ---
const baseSlugs = new Set();
for (const res of Object.values(g.resources || {})) {
  const slug = classToSlug[res.item];
  if (slug) baseSlugs.add(slug);
}
const baseItems = [...baseSlugs];
const infinite = ["water"];

const out = `// GENERATED by _data/generate.cjs from greeny/SatisfactoryTools data.json (1.0+) — do not edit by hand.
import type { Db } from "./types";

export const GAME_DB: Db = ${JSON.stringify({ items, recipes })};

/** Raw resources (ores + liquids) extracted from the game. */
export const BASE_ITEMS: string[] = ${JSON.stringify(baseItems)};

/** Unlimited resources → zero cost for the optimizer (water). */
export const INFINITE_ITEMS: string[] = ${JSON.stringify(infinite)};
`;

fs.writeFileSync(path.join(__dirname, "..", "src", "model", "game-db.ts"), out);
console.log(`[gen] ${Object.keys(items).length} items, ${Object.keys(recipes).length} machine recipes, ${baseItems.length} raw resources`);
const alts = Object.values(recipes).filter((r) => r.alternative).length;
console.log(`[gen] including ${alts} alternates, ${Object.keys(recipes).length - alts} standard`);
if (missingItems.size) console.warn(`[gen] ⚠️ ${missingItems.size} referenced items missing from g.items:`, [...missingItems].slice(0, 10).join(", "));
